// account_to_row_maps_correctly
// account_from_row_maps_correctly
// account_from_row_rejects_invalid_uuid
// account_from_row_rejects_invalid_currency
// account_from_row_rejects_invalid_account_type